#!/usr/bin/env bash
# Generate the agent wiki: what an agent needs to answer "where does X live?"
# without grepping the tree. Regenerate after any module add/remove/rename.
#
# Why this exists: three separate times in one session an agent rebuilt the
# module inventory by hand, at real token cost, because nothing on disk carried
# it. That is the RAG tax this file removes.
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="docs/wiki"
BIN="./target/release/physis-pro"
mkdir -p "$OUT"

# ── 1. Module map: one line per module, from its own //! header ──────────────
{
  echo "# Module map"
  echo
  echo "Generated by \`scripts/gen-wiki.sh\`. One line per module, taken from the"
  echo "module's own \`//!\` header. **Read this before grepping.**"
  echo
  echo "See \`docs/WHAT_PHYSIS_IS.md\` §3 for which of the six operations each serves."
  for tree in physis-core physis_pro; do
    case "$tree" in
      physis-core) dir="physis-core/src"; lic="Apache-2.0" ;;
      physis_pro)  dir="src";             lic="proprietary" ;;
    esac
    n=$(find "$dir" -name '*.rs' | wc -l)
    loc=$(find "$dir" -name '*.rs' -exec cat {} + | wc -l)
    echo
    echo "## $tree — $n modules, $loc lines, $lic"
    echo
    echo '| module | lines | what it does |'
    echo '|---|---:|---|'
    find "$dir" -name '*.rs' | sort | while read -r f; do
      rel="${f#"$dir"/}"
      case "$rel" in lib.rs|main.rs) continue ;; esac
      d=$(grep -m1 '^//! ' "$f" 2>/dev/null | sed 's|^//! ||; s/|/\\|/g' || true)
      l=$(wc -l < "$f" | tr -d ' ')
      printf '| `%s` | %s | %s |\n' "$rel" "$l" "${d:-—}"
    done
  done
} > "$OUT/MODULE_MAP.md"

# ── 2. What is deliberately NOT generated ───────────────────────────────────
# A symbol index. It was built once and measured: 3996 lines, ~26k tokens, and
# it answers exactly the question `grep -rn "fn select_embedder"` answers for
# ~50 tokens against fresher data. A wiki page earns its keep only when reading
# it is cheaper than the search it replaces. The module map clears that bar
# (~4.4k tokens, and it replaced three hand-rebuilt inventories in one session);
# a symbol dump does not.

wc -l "$OUT"/*.md
