#!/usr/bin/env bash
# Generate the module map: what an agent needs to answer "where does X live?"
# without grepping the tree. Regenerate after any module add/remove/rename.
#
# Why this exists: three separate times in one session an agent rebuilt the
# module inventory by hand, at real token cost, because nothing on disk carried
# it. That is the RAG tax this file removes.
#
# Usage: gen-wiki.sh [dir ...]                 (default: the current tree)
#        OUT=path/MODULE_MAP.md gen-wiki.sh    (default: docs/wiki/MODULE_MAP.md)
#
# Deliberately NOT generated: a symbol index. One was built once and measured —
# 3996 lines, ~26k tokens — and it answers exactly what `grep -rn "fn foo"`
# answers for ~50 tokens against fresher data. A wiki page earns its keep only
# when reading it is cheaper than the search it replaces. The module map clears
# that bar (~4.4k tokens on physis-pro, and it replaced three hand-rebuilt
# inventories in one session); a symbol dump does not.
set -Eeuo pipefail

DIRS=("${@:-.}")
OUT="${OUT:-docs/wiki/MODULE_MAP.md}"
mkdir -p "$(dirname "$OUT")"

# Pull the module's own one-line self-description, in that language's idiom.
# Falls back through the forms so a file with none yields "—" rather than a
# stray line of code.
describe() {
  local f="$1"
  case "$f" in
    *.rs) grep -m1 '^//! ' "$f" 2>/dev/null | sed 's|^//! ||' ;;
    *.py) python3 - "$f" <<'PY' 2>/dev/null
import ast,sys
try:
    d=ast.get_docstring(ast.parse(open(sys.argv[1],encoding='utf-8',errors='replace').read()))
    print((d or '').strip().splitlines()[0] if d else '')
except Exception:
    print('')
PY
      ;;
    *.go) grep -m1 '^// Package ' "$f" 2>/dev/null | sed 's|^// ||' ;;
    *)    grep -m1 -E '^\s*(\*|//) [A-Z]' "$f" 2>/dev/null | sed -E 's|^\s*(\*|//) ||' ;;
  esac | sed 's/|/\\|/g' | cut -c1-160
}

count=0
{
  echo "# Module map"
  echo
  echo "Generated by \`gen-wiki.sh\` over: ${DIRS[*]}. One line per module, taken"
  echo "from the module's own header comment or docstring. **Read this before grepping.**"

  for glob in '*.rs' '*.py' '*.ts' '*.tsx' '*.js' '*.go'; do
    files=$(find "${DIRS[@]}" \( -name node_modules -o -name target -o -name .git \
            -o -name dist -o -name build -o -name vendor -o -name __pycache__ \
            -o -name .venv \) -prune -o -name "$glob" -type f -print 2>/dev/null | sort) || true
    [ -n "$files" ] || continue
    n=$(printf '%s\n' "$files" | wc -l | tr -d ' ')
    loc=$(printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 cat 2>/dev/null | wc -l | tr -d ' ')
    count=$((count + n))
    echo
    echo "## ${glob#\*.} — $n modules, $loc lines"
    echo
    echo '| module | lines | what it does |'
    echo '|---|---:|---|'
    printf '%s\n' "$files" | while read -r f; do
      case "$(basename "$f")" in lib.rs|main.rs|__init__.py|index.ts|index.js) continue ;; esac
      printf '| `%s` | %s | %s |\n' "${f#./}" "$(wc -l < "$f" | tr -d ' ')" "$(describe "$f" || true)"
    done
  done
} > "$OUT"

# Rule 6: print the denominator, and refuse to call an empty map a result.
if [ "$(grep -c '^| `' "$OUT" || true)" = "0" ]; then
  echo "NO MODULES FOUND in: ${DIRS[*]} — $OUT is empty. Not a clean result." >&2
  exit 2
fi
wc -l "$OUT"
echo "tokens ≈ $(( $(wc -c < "$OUT") / 4 )) — if reading it costs more than the greps"
echo "it replaces, do not commit it."
